### ISSUE TITLE
Copy Paste Conditions - Uncaught TypeError: bricksPanel is null

### ISSUE THREAD

**Issue by xenio** [0jscsshtml/Bricksfree#1]
Hello, I was trying to add your Copy Paste Conditions javascript to my setup, but I am getting this error:

![Screen Shot 2024-03-15 at 08 47 35](https://github.com/0jscsshtml/Bricksfree/assets/153355/faac7d08-4c55-4c3e-85da-2db24cee19bc)
Uncaught TypeError: bricksPanel is null
There is the console log that show first time null and the second time is not null, I don't know why it is called two times.

The js file is enqueued with: wp_enqueue_script 
under this condition:
bricks_is_builder_main() || function_exists('bricks_is_builder_main'

I am also using Copy Attributes and it is working well.

**Comment by 0jscsshtml** [comment]
I enqueue my script like below in my pulgin, no issue
`public function enqueue_builder_scripts() {
		if ( bricks_is_builder_main() ) {
		    wp_enqueue_script('my-script', BRICKSFREE_URL . 'includes/js/my-script.js', ['bricks-scripts', 'underscore', 'backbone', 'bricks-builder', 'jquery'], '', true);
		}
add_action( 'wp_enqueue_scripts',  [ $this, 'enqueue_builder_scripts' ], 11 );`

**Comment by xenio** [comment]
Thanks, it is working now... but I had this error after your enqueue script:

`Uncaught ReferenceError: can't access lexical declaration 'condCopyBtn' before initialization`

Removing const from line 44 solved the problem.
`const condCopyBtn = condCopyBtn();`

Thanks!

**Comment by 0jscsshtml** [comment]
great, make changes on line 44 & 45. Thanks
